This section is about testing exception handling in Python. Maybe you want to test that a function raises an exception when it should, or maybe you want to test that a function does not raise an exception when it should not. This section will show you how to do both. It's also possible to assert certain properties of the exception that is raised, such as the exception message or the exception type.

::: tests.test_exceptions.function_that_raises
::: tests.test_exceptions.CustomException
::: tests.test_exceptions.TestExceptionHandling
